name: mynoteactions
on: 
  workflow_dispatch:
jobs:
  update-activity:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: sh index.sh
      - uses: stefanzweifel/git-auto-commit-action@v4